In [1]:
#google colab doesn't come with torch installed :(
!pip3 install torch

In [2]:
#gotta import it of course, and numpy, a library with shared philosophy and interoperability
import torch
import numpy as np

In [4]:
#creates tensor, this is an idiomatic, basic way not using range
v = torch.tensor([1,2,3,4,5,6])

#indexing of tensors, the stop index is exclusive(Pythonic in this sense)
print(v[1:4])

tensor([2, 3, 4])


In [5]:
#float tensor -- a tensor of...floats, whoa
f = torch.FloatTensor([1,2,3,4,5,6])
print(f)

tensor([1., 2., 3., 4., 5., 6.])


In [6]:
print(f.dtype)

torch.float32


In [8]:
#.size() gives the size of a tensor, dead simple
print(f.size())

torch.Size([6])


In [9]:
#view tensor as 6 rows in 1 column, ala. numpy's reshape method
v.view(6,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [10]:
#viewing tensor as 3 rows w/2 columns...
v.view(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [11]:
v.view(3,-1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [14]:
#creating a numpy n-dimensional array(type: ndarray)
a = np.array([1,2,3,4,5])

In [15]:
#creating a tensor from a numpy array!
tensor_cnv = torch.from_numpy(a)
print(tensor_cnv)

tensor([1, 2, 3, 4, 5])


In [16]:
#another way of giving the type
print(tensor_cnv.type())

torch.LongTensor


In [17]:
#whoa, turning it back into an ndarray! wild stuff,,,
numpy_cnv = tensor_cnv.numpy()
print(numpy_cnv)

[1 2 3 4 5]


In [18]:
#interchangable between numpy arrays and tensors

In [21]:
print(type(numpy_cnv))

<class 'numpy.ndarray'>
